# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-23 13:19


import datetime
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', django.contrib.postgres.fields.jsonb.JSONField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('DELIVERED', 'Delivered'), ('DELIVERY FAILURE', 'Delivery Failure')], max_length=16)),
                ('scheduled_delivery', models.DateTimeField()),
                ('attempted_delivery', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notifications_notification',
                'verbose_name_plural': 'Notifications',
            },
        ),
        migrations.CreateModel(
            name='OptOut',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start', models.DateField(default=django.utils.timezone.now)),
                ('end', models.DateField(default=datetime.date(2999, 12, 31))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications_opt_out',
                'verbose_name_plural': 'Opt Outs',
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('class_name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserTarget',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_target_id', models.CharField(max_length=200)),
                ('user_target_friendly_name', models.CharField(max_length=50)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='notifications.Target')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications_user_target',
                'verbose_name_plural': 'User Targets',
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='user_target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='notifications.UserTarget'),
        ),
        migrations.AlterUniqueTogether(
            name='usertarget',
            unique_together=set([('user', 'target', 'user_target_id')]),
        ),
    ]
