# Generated by Django 2.1.7 on 2019-04-12 16:00

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import website.notifications.models.notification


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20190306_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_object_uuid',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='extra',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=website.notifications.models.notification.get_default_data, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('DELIVERED', 'Delivered'), ('DELIVERY FAILURE', 'Delivery Failure')], max_length=16),
        ),
    ]
