# Generated by Django 2.1.7 on 2019-05-14 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_auto_20190418_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='max_retries',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='notification',
            name='retry_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notification',
            name='time_interval',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('DELIVERED', 'Delivered'), ('DELIVERY FAILURE', 'Delivery Failure'), ('RETRY', 'Retry')], max_length=16),
        ),
    ]
