# Generated by Django 2.1.7 on 2019-05-15 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_auto_20190514_1419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='time_interval',
            new_name='retry_time_interval',
        ),
    ]
