# Generated by Django 2.1.9 on 2019-07-10 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_auto_20190515_0848'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notification',
            unique_together={('user_target', 'scheduled_delivery', 'title')},
        ),
    ]
