# Generated by Django 2.2.7 on 2019-11-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0010_auto_20190911_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='optout',
            name='has_opted_out',
            field=models.BooleanField(default=True),
        ),
    ]
