# Generated by Django 2.2.7 on 2019-11-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0011_optout_has_opted_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optout',
            name='has_opted_out',
            field=models.BooleanField(default=False),
        ),
    ]
