# Generated by Rocky on 2020-01-30 19:53
from django.db.models import Subquery, OuterRef
from django.db import migrations, models


def sush_duplicate_user_targets(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    UserTarget = apps.get_model("notifications", "UserTarget")

    db_alias = schema_editor.connection.alias
    UserTarget.objects.using(db_alias).filter()

    newest = UserTarget.objects.filter(
        target__class_name=OuterRef("target__class_name"),
        user=OuterRef("user"),
        user_target_friendly_name=OuterRef("user_target_friendly_name"),
    ).order_by("-created_date")

    UserTarget.objects.filter(
        created_date__lt=Subquery(newest.values("created_date")[:1])
    ).update(active=False,)


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0012_auto_20191115_1331"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertarget",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(sush_duplicate_user_targets),
    ]
