# Generated by Django 2.2.8 on 2020-01-31 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0013_usertarget_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('DELIVERED', 'Delivered'), ('DELIVERY FAILURE', 'Delivery Failure'), ('RETRY', 'Retry'), ('INACTIVE DEVICE', 'Inactive Device')], max_length=16),
        ),
    ]
