# Generated by Django 2.2.8 on 2020-02-06 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0015_auto_20200203_1040'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notification',
            unique_together={('user_target', 'scheduled_delivery', 'title', 'extra')},
        ),
    ]
