# Generated by Django 3.1.3 on 2020-11-30 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_notification_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='target',
            options={'verbose_name_plural': 'Targets'},
        ),
        migrations.RenameField(
            model_name='optout',
            old_name='has_opted_out',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='target',
            old_name='class_name',
            new_name='notification_creator_module',
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('DELIVERED', 'Delivered'), ('DELIVERY FAILURE', 'Delivery Failure'), ('INACTIVE DEVICE', 'Inactive Device'), ('OPTED OUT', 'Opted Out'), ('RETRY', 'Retry'), ('SCHEDULED', 'Scheduled')], max_length=16),
        ),
        migrations.AlterField(
            model_name='target',
            name='name',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterModelTable(
            name='target',
            table='notification_system_target',
        ),
    ]
