# Generated by Django 3.1.3 on 2020-11-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_notification_system', '0002_auto_20201130_2015'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='usertarget',
            name='user target ids cannot be repeated',
        ),
        migrations.RemoveConstraint(
            model_name='usertarget',
            name='Only one active user target per friendly name',
        ),
        migrations.RenameField(
            model_name='usertarget',
            old_name='user_target_id',
            new_name='target_user_id',
        ),
        migrations.RemoveField(
            model_name='usertarget',
            name='user_target_friendly_name',
        ),
        migrations.AddField(
            model_name='usertarget',
            name='description',
            field=models.CharField(default='EGGS', max_length=200),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='usertarget',
            constraint=models.UniqueConstraint(fields=('user', 'target', 'target_user_id'), name='user target ids cannot be repeated'),
        ),
    ]
